// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoOKRHPYl_ZQXNRDivMeyWs7qu87AVtFc',
    appId: '1:288341099904:web:a2b29d59d34860ace26d65',
    messagingSenderId: '288341099904',
    projectId: 'zenly-like-app',
    authDomain: 'zenly-like-app.firebaseapp.com',
    storageBucket: 'zenly-like-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA969D8qDlr_4kXa4jKjdmPQz8HjRuCgi0',
    appId: '1:288341099904:android:c926262281ffc729e26d65',
    messagingSenderId: '288341099904',
    projectId: 'zenly-like-app',
    storageBucket: 'zenly-like-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQGloGwKPukgC2HQSimQA7vAPwwdN-e3A',
    appId: '1:288341099904:ios:13791dd0345b9cf1e26d65',
    messagingSenderId: '288341099904',
    projectId: 'zenly-like-app',
    storageBucket: 'zenly-like-app.appspot.com',
    iosClientId: '288341099904-j85m56g6ln6vt9r3tshel17v2l20s0lo.apps.googleusercontent.com',
    iosBundleId: 'com.example.zenlyLikeApp',
  );
}
